[package]
name = "shc"
version = "0.1.0"
edition = "2021"

[dependencies]
md5 = "0.7.0"
sha1 = "0.11.0-pre.3"
sha2 = "0.11.0-pre.3"
crc32fast = "1.4.0"
termcolor = "1.4.1"
hex = "0.4.3"

[profile.release]
strip = true
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'